/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libdivecomputer_Parser */

#ifndef _Included_org_libdivecomputer_Parser
#define _Included_org_libdivecomputer_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libdivecomputer_Parser
 * Method:    New
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_org_libdivecomputer_Parser_New
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_libdivecomputer_Parser
 * Method:    New2
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_org_libdivecomputer_Parser_New2
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     org_libdivecomputer_Parser
 * Method:    Foreach
 * Signature: (JLorg/libdivecomputer/Parser/Callback;)V
 */
JNIEXPORT void JNICALL Java_org_libdivecomputer_Parser_Foreach
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_libdivecomputer_Parser
 * Method:    GetDatetime
 * Signature: (JLorg/libdivecomputer/Parser/Datetime;)V
 */
JNIEXPORT void JNICALL Java_org_libdivecomputer_Parser_GetDatetime
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
