/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libdivecomputer_IOStream */

#ifndef _Included_org_libdivecomputer_IOStream
#define _Included_org_libdivecomputer_IOStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libdivecomputer_IOStream
 * Method:    Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_libdivecomputer_IOStream_Close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
