/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libdivecomputer_Serial */

#ifndef _Included_org_libdivecomputer_Serial
#define _Included_org_libdivecomputer_Serial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libdivecomputer_Serial
 * Method:    Open
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_libdivecomputer_Serial_Open
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
