/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libdivecomputer_Custom */

#ifndef _Included_org_libdivecomputer_Custom
#define _Included_org_libdivecomputer_Custom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libdivecomputer_Custom
 * Method:    Open
 * Signature: (JILorg/libdivecomputer/Custom/Callback;)J
 */
JNIEXPORT jlong JNICALL Java_org_libdivecomputer_Custom_Open
  (JNIEnv *, jobject, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
